import React from 'react';

const PrivacyPolicyPage = () => {
  return (
    <div className="bg-white py-32 text-black">
      <div className="container mx-auto">
        <h1 className="text-black">AGB</h1>
        <h4>1. Geltungsbereich und Vertragsparteien</h4>
        <p><strong>1.1. Anwendungsbereich dieser Geschäftsbedingungen:</strong> Diese Allgemeinen Geschäftsbedingungen (nachfolgend <strong>AGB</strong>) regeln sämtliche Vereinbarungen über die temporäre Überlassung von Wohnungen und Apartments zum Zweck der Beherbergung, die zwischen der <strong>Cozy Voyage GmbH</strong> (im Folgenden auch <strong>Cozy Voyage</strong>) und Dritten (nachfolgend <strong>Gast</strong> genannt) getroffen werden. Sie umfassen ebenfalls alle weiteren Dienstleistungen und Lieferungen, die Cozy Voyage in diesem Zusammenhang erbringt.</p>
        <p><strong>1.2. Ihr Vertragspartner:</strong> Ihr Vertragspartner ist stets die <strong>Cozy Voyage GmbH</strong>.</p>
        <p><strong>1.3. Abweichende Kundenbedingungen:</strong> Kundenbedingungen finden nur dann Anwendung, wenn Cozy Voyage deren Geltung vorab explizit und in schriftlicher Form zugestimmt hat.</p>

        ---
        <h4>2. Buchungsprozess</h4>
        <p><strong>2.1. Abschluss des Beherbergungsvertrags:</strong> Durch das Tätigen einer Reservierung oder Buchung gibt der Gast ein verbindliches Angebot zum Abschluss eines Beherbergungsvertrags ab. Cozy Voyage sendet dem Gast eine Bestätigung der Reservierung/Buchung zu, sofern das gewünschte Apartment verfügbar ist. Mit dieser Bestätigung kommt der Beherbergungsvertrag zwischen Cozy Voyage und dem Gast wirksam zustande.</p>
        <p><strong>2.2. Unverbindlichkeit von Angeboten:</strong> Alle Verfügbarkeitsangebote von Cozy Voyage für Apartments sind freibleibend und stellen keine bindenden Zusagen dar. Cozy Voyage behält sich das Recht vor, den Abschluss eines Beherbergungsvertrags nach eigenem Ermessen abzulehnen.</p>
        <p><strong>2.3. Kategoriebuchungen und Einschränkungen:</strong> Sofern der Gast lediglich eine Apartmentkategorie bucht, besteht kein Anspruch auf ein spezifisches Apartment innerhalb dieser Kategorie. Branchenübliche Einschränkungen wie Mindestaufenthalte, Buchungsgarantien oder Vorauszahlungen für bestimmte Reisezeiten behält sich Cozy Voyage vor.</p>

        ---
        <h4>3. Stornierungsbedingungen, Rücktritt und Nichtanreise</h4>
        <p><strong>3.1. Garantierte Buchungen und Stornierungen:</strong> Eine Buchung gilt erst mit der vollständigen Zahlung des Gastes an Cozy Voyage als garantiert. Der Gast kann garantierte Buchungen kostenfrei stornieren, sofern dies innerhalb der kommunizierten Stornierungsbedingungen und Fristen sowie unter Angabe der zugehörigen Reservierungsnummer geschieht. Ist ein Rücktrittsrecht nicht vereinbart worden oder ist eine kostenfreie Stornierungsfrist abgelaufen, besteht weder ein gesetzliches Rücktritts- noch ein Kündigungsrecht und stimmt Cozy Voyage einer vorzeitigen Vertragsaufhebung nicht zu, bleibt der Anspruch auf die vereinbarte Vergütung auch bei Nichtanreise (<strong>No-Show</strong>) oder verspäteter Stornierung bestehen. Cozy Voyage wird jedoch Einnahmen aus einer anderweitigen Vermietung des Apartments sowie ersparte Aufwendungen anrechnen. Sollte das Apartment nicht anderweitig vermietet werden können, ist Cozy Voyage berechtigt, die ersparten Aufwendungen pauschal zu berechnen. In diesem Fall ist der Gast verpflichtet, <strong>90%</strong> des ursprünglich vereinbarten Übernachtungspreises zu entrichten. Dem Gast bleibt es unbenommen, nachzuweisen, dass kein oder ein wesentlich geringerer Schaden entstanden ist. Bei Nichtanreise des Gastes für mehrtägig garantierte Buchungen werden alle weiteren Nächte ab der ersten Nacht storniert, und der Gast hat keinen Anspruch auf die Übernachtung in den Folgnächten.</p>
        <p><strong>3.2. Zahlungsfristen bei kurzfristigen Reservierungen:</strong> Bei Reservierungen, die am Tag der Anreise erfolgen, hat der Gast die vollständige Zahlung gemäß Ziffer 5 für den gesamten Aufenthalt umgehend, in der Regel innerhalb einer Stunde, zu leisten.</p>

        ---
        <h4>4. Preise für Übernachtungen und Zusatzleistungen</h4>
        <p><strong>4.1. Gültigkeit der Preise:</strong> Es gelten die von Cozy Voyage zum Zeitpunkt des Vertragsabschlusses angegebenen Preise. Alle ausgewiesenen Preise verstehen sich als Bruttopreise und beinhalten sämtliche gesetzlichen Steuern, Gebühren und Abgaben. Lokale Abgaben, die direkt vom Gast zu tragen sind (z.B. Kurtaxen), sind nicht im Übernachtungspreis enthalten.</p>

        ---
        <h4>5. Zahlungsmodalitäten und Rechnungsstellung</h4>
        <p><strong>5.1. Vorauszahlung:</strong> Der Preis für die vom Gast gebuchte Übernachtungsleistung ist grundsätzlich im Voraus vom Gast zu begleichen.</p>
        <p><strong>5.2. Ausschluss der Aufrechnung:</strong> Eine Aufrechnung durch den Gast ist ausgeschlossen, es sei denn, die Forderung ist unbestritten oder rechtskräftig festgestellt.</p>
        <p><strong>5.3. Akzeptierte Zahlungsmittel:</strong> Cozy Voyage akzeptiert folgende Zahlungsmittel: <strong>MasterCard, Visa, American Express, Sofortüberweisung/Klarna, Paypal oder reguläre Banküberweisung</strong>. Barzahlungen können nicht angenommen werden.</p>
        <p><strong>5.4. Belastung hinterlegter Zahlungsmittel:</strong> Cozy Voyage behält sich das Recht vor, die hinterlegten Zahlungsmethoden des Gastes mit Beträgen für zusätzliche Leistungen oder bei Verstößen gegen diese AGB zu belasten. Der Gast erteilt Cozy Voyage hierfür ausdrücklich die Genehmigung.</p>
        <p><strong>5.5. Elektronische Rechnungsstellung:</strong> Mit der Reservierung erklärt sich der Gast damit einverstanden, seine Rechnung in digitaler Form (als Download oder per E-Mail) zu erhalten.</p>

        ---
        <h4>6. Nutzung des reservierten Apartments</h4>
        <p><strong>6.1. Verfügbarkeit des Apartments:</strong> Das reservierte Apartment steht dem Gast für den in der Buchung festgelegten Zeitraum zur Verfügung.</p>
        <p><strong>6.2. Rückgabe von Zugangsmitteln:</strong> Sämtliche von Cozy Voyage bereitgestellte <strong>Schlüssel, Parkausweise und/oder Schlüsselkarten</strong> sind am Abreisetag an Cozy Voyage, einem von Cozy Voyage benannten Dritten oder an den durch Cozy Voyage gekennzeichneten bzw. mitgeteilten Ablageort im Apartment zurückzugeben. Bei Verlust eines Schlüssels, einer Schlüsselkarte oder eines Parkausweises sowie bei Nichtrückgabe dieser Gegenstände wird eine Gebühr von <strong>40,00€</strong> fällig. Cozy Voyage ist weiter berechtigt, zusätzlichen Schadensersatz vom Gast zu fordern, sofern der tatsächliche Schaden 40,00€ übersteigt. Dies kann auch den Austausch der betroffenen Schließanlage umfassen, falls dies aus Sicherheitsgründen notwendig ist. Dem Gast steht es frei, nachzuweisen, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>6.3. Spätere Abreise (Late Check-out):</strong> Eine spätere Abreise kann auf Anfrage und nach Verfügbarkeit zwischen Cozy Voyage und dem Gast vereinbart werden. Erfolgt eine Zustimmung zum Late Check-out, berechnet Cozy Voyage <strong>10,00€ pro angefangene Stunde</strong> für die zusätzliche Nutzung des Apartments. Ohne vorherige Zustimmung von Cozy Voyage wird für jede angefangene Stunde eine Gebühr von <strong>30,00€</strong> erhoben. Bei einer Abreise, die mehr als 3 Stunden nach der ursprünglich vereinbarten Check-out-Zeit liegt, wird bei vorheriger Zustimmung von Cozy Voyage der volle Übernachtungspreis des Apartments berechnet. Ohne Zustimmung schuldet der Gast neben dem vollen Übernachtungspreis auch den Ersatz des darüber hinausgehenden Schadens. Dem Gast ist der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>6.4. Kein Anspruch auf Late Check-out:</strong> Ein vertraglicher Anspruch auf einen Late Check-out besteht für den Gast nicht.</p>
        <p><strong>6.5. Frühere Anreise (Early Check-in):</strong> Eine frühere Anreise kann auf Anfrage und nach Verfügbarkeit zwischen Cozy Voyage und dem Gast vereinbart werden. Stimmt Cozy Voyage einem Early Check-in zu, werden <strong>10,00€ pro angefangene Stunde</strong> für die zusätzliche Nutzung des Apartments in Rechnung gestellt. Ein vertraglicher Anspruch auf einen Early Check-in kann vom Gast nicht hergeleitet werden.</p>

        ---
        <h4>7. Nutzung und Weitergabe von Apartments</h4>
        <p><strong>7.1. Untersagte Weitervermietung und -vermittlung:</strong> Die Weitervermietung oder Weitervermittlung des gebuchten Apartments ist strikt untersagt. Dies schließt insbesondere die Weitervermittlung von Apartments oder Apartmentkontingenten an Dritte zu Preisen ein, die höher sind als die von Cozy Voyage ausgewiesenen. Die Abtretung oder der Verkauf von Ansprüchen gegen Cozy Voyage ist ebenfalls nicht gestattet. Bei Zuwiderhandlung ist Cozy Voyage berechtigt, die Reservierung zu stornieren, insbesondere wenn der Gast Dritten gegenüber unwahre Angaben über die Art der Buchung oder die Bezahlung gemacht hat.</p>
        <p><strong>7.2. Zweckbindung der Nutzung:</strong> Die Apartments von Cozy Voyage dürfen ausschließlich zu Beherbergungszwecken genutzt werden. Jegliche kommerzielle oder illegale Nutzung ist ausdrücklich untersagt. Foto- oder Videoaufnahmen in den Apartments sind ohne explizite Genehmigung ebenfalls nicht erlaubt. Im Falle einer Nutzung, die nicht der Beherbergung dient, behält sich Cozy Voyage das Recht vor, die Reservierung ohne Rückerstattung zu stornieren und das Apartment räumen zu lassen.</p>

        ---
        <h4>8. Haftungsregelungen für Cozy Voyage</h4>
        <p><strong>8.1. Umfang der Haftung:</strong> Cozy Voyage haftet uneingeschränkt für Schäden, die aus der Verletzung des Lebens, des Körpers oder der Gesundheit resultieren und von ihr zu vertreten sind. Für sonstige Schäden, die auf einer vorsätzlichen oder grob fahrlässigen Pflichtverletzung von Cozy Voyage beruhen, haftet Cozy Voyage ebenfalls vollumfänglich. Bei einfacher Fahrlässigkeit ist die Haftung von Cozy Voyage auf den vertragstypisch vorhersehbaren Schaden begrenzt, sofern eine Pflicht verletzt wird, deren Erfüllung für die ordnungsgemäße Vertragsdurchführung unerlässlich ist und auf deren Einhaltung der Gast vertrauen darf (sogenannte <strong>Kardinalspflicht</strong>). Eine Pflichtverletzung von Cozy Voyage steht der seiner gesetzlichen Vertreter, Angestellten oder Erfüllungsgehilfen gleich. Weitergehende Schadensersatzansprüche sind, soweit in diesen AGB nicht anders geregelt, ausgeschlossen.</p>
        <p><strong>8.2. Mängelanzeige und Mitwirkungspflicht des Gastes:</strong> Bei Störungen oder Mängeln an den Leistungen von Cozy Voyage wird Cozy Voyage auf unverzügliche Rüge des Gastes oder bei eigener Kenntnis umgehend Abhilfe schaffen. Der Gast ist verpflichtet, das ihm Zumutbare beizutragen, um die Störung oder den Mangel zu beheben und mögliche Schäden zu minimieren. Der Gast muss Cozy Voyage zudem unverzüglich auf die Möglichkeit der Entstehung eines hohen Schadens hinweisen.</p>
        <p><strong>8.3. Haftung für eingebrachte Gegenstände:</strong> Cozy Voyage haftet für eingebrachte Sachen nach den gesetzlichen Bestimmungen. Ein etwaiger Anspruch des Gastes erlischt, wenn er den Verlust, die Zerstörung oder Beschädigung nicht unverzüglich nach Kenntniserlangung bei Cozy Voyage anzeigt, es sei denn, eine verspätete Anzeige hätte keine Auswirkungen auf die Sachverhaltsklärung. Für die Einbringung von Geldmitteln, Wertgegenständen oder sonstigen Kostbarkeiten, deren Wert <strong>800,00€</strong> übersteigt, oder für sonstige Gegenstände mit einem Wert von mehr als <strong>3.500,00€</strong>, ist eine gesonderte schriftliche Vereinbarung mit Cozy Voyage erforderlich. Andernfalls ist eine Haftung von Cozy Voyage für den Verlust, die Zerstörung oder Beschädigung dieser Mittel oder Gegenstände ausgeschlossen.</p>
        <p><strong>8.4. Haftung für Parkplätze:</strong> Die entgeltliche oder unentgeltliche Bereitstellung eines Stellplatzes durch Cozy Voyage begründet keinen Verwahrungsvertrag. Eine Überwachungspflicht für Cozy Voyage entsteht hieraus nicht. Cozy Voyage haftet für das Abhandenkommen, den Diebstahl oder die Beschädigung von auf dem Grundstück und/oder dem zur Verfügung gestellten Stellplatz abgestellten oder rangierten Kraftfahrzeugen ausschließlich bei Vorsatz oder grober Fahrlässigkeit. Der Gast ist verpflichtet, Schäden unverzüglich anzuzeigen. Offensichtliche Schäden müssen in jedem Fall vor Verlassen des Stellplatzes gemeldet werden. Cozy Voyage haftet nicht für Schäden, die ausschließlich von anderen Gästen oder sonstigen Dritten verursacht wurden.</p>
        <p><strong>8.5. Verjährung von Ansprüchen:</strong> Sämtliche Ansprüche gegenüber Cozy Voyage verjähren grundsätzlich innerhalb eines Jahres ab dem gesetzlichen Verjährungsbeginn. Ausgenommen hiervon sind Schadensersatzansprüche oder sonstige Ansprüche aus der Verletzung von Leben, Körper oder Gesundheit und/oder aufgrund grob fahrlässiger oder vorsätzlicher Pflichtverletzung durch Cozy Voyage, sowie im Falle der Verletzung einer Kardinalspflicht.</p>
        <p><strong>8.6. Fundsachen:</strong> Cozy Voyage übernimmt keine Haftung für Fundsachen, es sei denn, die Haftung beruht auf vorsätzlichen oder grob fahrlässigen Pflichtverletzungen von Cozy Voyage. Fundsachen werden ausschließlich auf Anfrage, gegen Entgelt und eine zusätzliche Bearbeitungsgebühr von <strong>15,00€</strong>, zurückgesendet. Cozy Voyage bewahrt Fundsachen für einen Zeitraum von sechs Monaten auf, danach erfolgt deren Entsorgung.</p>

        ---
        <h4>9. Kaution</h4>
        <p><strong>9.1. Erhebung einer Sicherheitsleistung:</strong> Zur Absicherung aller Ansprüche von Cozy Voyage gegenüber dem Gast, die sich aus dem Beherbergungsvertrag ergeben, ist Cozy Voyage berechtigt, vor der Apartmentüberlassung folgende Sicherheitsleistungen/Kautionen vom Gast zu verlangen:</p>
        <p><strong>9.2. Kautionshöhe bei kürzeren Aufenthalten:</strong> Bei einer Aufenthaltsdauer von weniger als drei Monaten beträgt die Kaution <strong>250,00€</strong>.</p>
        <p><strong>9.3. Kautionshöhe bei längeren Aufenthalten:</strong> Bei einer Aufenthaltsdauer von drei bis sechs Monaten entspricht die Kaution einem monatlichen Übernachtungspreis.</p>
        <p><strong>9.4. Kautionsstellung und Recht zur Kündigung:</strong> Für Aufenthalte von weniger als drei Monaten ist Cozy Voyage berechtigt, die Kaution/Sicherheitsleistung durch eine Vorabautorisierung des Zahlungsmittels zu sichern. Leistet der Gast die Kaution/Sicherheitsleistung nicht, besteht kein Anspruch auf den Aufenthalt im Apartment. Sollte Cozy Voyage dem Gast das Apartment trotz fehlender Kautionsstellung überlassen haben, ist Cozy Voyage zur fristlosen Kündigung des Beherbergungsvertrages berechtigt, wenn die Kaution nicht innerhalb einer angemessenen, zu setzenden Nachfrist geleistet wird.</p>
        <p><strong>9.5. Abrechnung der Kaution:</strong> Cozy Voyage ist verpflichtet, die Kaution innerhalb eines Monats nach Beendigung des Beherbergungsvertrages abzurechnen.</p>

        ---
        <h4>10. Erfassung und Nutzung von Kundendaten</h4>
        <p><strong>10.1. Erfassung von Kontaktdaten und Identitätsprüfung:</strong> Cozy Voyage erfasst verpflichtend die E-Mail-Adresse und Telefonnummer des Gastes zur Sicherstellung der Kommunikation. Cozy Voyage ist zudem berechtigt, beim Check-in ein gültiges Identifikationsdokument in digitaler Form anzufordern. Für inländische Gäste ist dies ein Personalausweis oder Reisepass; für ausländische Gäste ist stets ein Reisepass vorzulegen.</p>
        <p><strong>10.2. Stornierung bei unklarer Identität:</strong> Sollte die Identität eines Gastes aufgrund fehlender oder falscher Dokumente nicht zweifelsfrei festgestellt werden können, ist Cozy Voyage berechtigt, die Buchung zu stornieren.</p>
        <p><strong>10.3. Recht zur Buchungsstornierung:</strong> Cozy Voyage ist berechtigt, die Buchung eines Gastes zu stornieren, falls die Identität des Gastes aufgrund fehlender oder unrichtiger Dokumente nicht eindeutig geklärt werden kann.</p>
        <p><strong>10.4. Betrugsprävention:</strong> Zur Vermeidung betrügerischer oder schadhafter Buchungen setzt Cozy Voyage Softwarelösungen ein, die anhand der vom Gast bereitgestellten Daten (E-Mail-Adresse, Telefonnummer, Kreditkartendaten, Anschrift) einen "Fraud-Prevention-Score" für jeden Gast ermitteln. Cozy Voyage behält sich das Recht vor, Buchungen, die durch das System entsprechend markiert wurden, zu stornieren.</p>

        ---
        <h4>11. Beendigung des Beherbergungsvertrags</h4>
        <p><strong>11.1. Recht zur fristlosen Kündigung:</strong> Cozy Voyage behält sich das Recht vor, einen Beherbergungsvertrag aus wichtigem Grund fristlos zu kündigen. Ein wichtiger Grund liegt insbesondere dann vor, wenn:</p>
        <ul>
          <li>höhere Gewalt oder andere Umstände, die Cozy Voyage nicht zu vertreten hat, die Vertragserfüllung unmöglich machen;</li>
          <li>Cozy Voyage begründeten Anlass zu der Annahme hat, dass die Inanspruchnahme der Beherbergungsleistung den reibungslosen Geschäftsbetrieb, die Sicherheit oder das öffentliche Image von Cozy Voyage und deren Standorten gefährden könnte, ohne dass dies dem Einfluss- oder Organisationsbereich von Cozy Voyage zuzurechnen ist;</li>
          <li>Buchungen schuldhaft unter irreführenden oder falschen Angaben oder durch das Verschweigen wesentlicher Tatsachen getätigt wurden; wesentlich können dabei, sind aber nicht beschränkt auf, die Identität des Gastes, dessen Zahlungsfähigkeit oder der Aufenthaltszweck sein;</li>
          <li>der Zweck oder Anlass des Aufenthalts gesetzeswidrig ist oder der Wohnungsprostitution dient;</li>
          <li>ein Fall der Weitervermietung, Weitervermittlung oder des Weiterverkaufs vorliegt (siehe Ziffer 7).</li>
        </ul>
        <p>Cozy Voyage muss den Gast unverzüglich über die Ausübung dieses Kündigungsrechts informieren.</p>
        <p><strong>11.2. Ausschluss von Schadensersatzansprüchen bei berechtigter Kündigung:</strong> Bei einer berechtigten Kündigung durch Cozy Voyage hat der Gast keinen Anspruch auf Schadensersatz.</p>
        <p><strong>11.3. Ablehnung zukünftiger Buchungen:</strong> Erfolgt eine Kündigung seitens Cozy Voyage aufgrund eines vom Gast zu vertretenden Umstands oder eines Grundes gemäß der oben genannten Ziffer 11.1, ist Cozy Voyage berechtigt, auch zukünftige Buchungen des Gastes zu stornieren oder abzulehnen, selbst wenn diese bereits bestätigt wurden.</p>

        ---
        <h4>12. Gutscheine</h4>
        <p><strong>12.1. Einlösbarkeit von Gutscheinen:</strong> Ein bei Cozy Voyage erworbener Gutschein kann ausschließlich für Leistungen von Cozy Voyage eingelöst werden. Verbleibende Restguthaben nach einer Zahlung mit dem Gutschein bleiben bestehen und können für weitere Buchungen genutzt werden.</p>
        <p><strong>12.2. Übertragbarkeit und Barauszahlung:</strong> Gutscheine sind von der Rückgabe ausgeschlossen, nicht weiterverkäuflich oder übertragbar und können weder ganz noch teilweise in Bargeld eingelöst werden.</p>
        <p><strong>12.3. Verantwortung für Bestellerdaten:</strong> Der Besteller des Gutscheins trägt die Verantwortung für die korrekte Angabe der Daten (insbesondere E-Mail-Adresse), an die der Gutschein und die Rechnung versendet werden sollen.</p>

        ---
        <h4>13. Rauchverbot und Sicherheitsvorschriften</h4>
        <p><strong>13.1. Allgemeines Rauchverbot:</strong> Alle Apartments und Gemeinschaftsbereiche von Cozy Voyage sind <strong>Nichtraucherbereiche</strong>. Das Rauchen ist in diesen Bereichen strengstens untersagt. Dies gilt auch für E-Zigaretten, Shishas, Tabakerhitzer und ähnliche Geräte.</p>
        <p><strong>13.2. Rauchen auf Balkonen/Terrassen:</strong> Das Rauchen auf Balkon- und/oder Terrassenbereichen ist nur gestattet, wenn diese entsprechend gekennzeichnet sind und die Tür zum Apartment geschlossen ist.</p>
        <p><strong>13.3. Folgen von Zuwiderhandlungen gegen das Rauchverbot:</strong> Bei Verstößen gegen das Rauchverbot ist Cozy Voyage berechtigt, vom Gast Schadensersatz für die erforderlichen Reinigungskosten sowie eventuelle Einnahmeausfälle durch eine daraus resultierende, nicht zumutbare Weitervermietung des Apartments zu fordern, mindestens jedoch <strong>EUR 250,00</strong>. Der Schadensersatzbetrag kann höher ausfallen, wenn Cozy Voyage einen höheren Schaden nachweist. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>13.4. Umgang mit Sicherheitseinrichtungen:</strong> Das Manipulieren oder Blockieren von Notausgängen, Feuerlöschern oder der Brand- und Hausalarmanlage ist untersagt. Bei Zuwiderhandlung wird eine Strafgebühr von <strong>150€</strong> fällig. Dies gilt auch für die Manipulation oder Deaktivierung von Sicherheits- und Dezibelsensoren innerhalb des Apartments.</p>
        <p><strong>13.5. Kündigungsrecht bei Sicherheitsverstößen:</strong> Cozy Voyage ist berechtigt, eine aktive Buchung mit sofortiger Wirkung zu kündigen und den Gast des Hauses zu verweisen, sobald Kenntnis von Zuwiderhandlungen gegen die Punkte 13.1 und 13.4 erlangt wird. In solchen Fällen besteht kein Anspruch auf Rück- oder Teilerstattung. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>13.6. Kosten bei Brandmeldeanlagen-Auslösung:</strong> In Gebäuden von Cozy Voyage können vernetzte Rauchmelder installiert sein, die direkt mit der Feuerwehr oder einem Sicherheitsdienst verbunden sind. Der Gast haftet im vollen Umfang für die vorsätzliche oder fahrlässige Auslösung der Brandmeldeanlage (z.B. durch Verstoß gegen das Rauchverbot), mindestens jedoch in Höhe der tatsächlich entstandenen Kosten (z.B. Einsatzkosten der Feuerwehr oder des Sicherheitsdienstes).</p>

        ---
        <h4>14. Verbot von Partys und Versammlungen</h4>
        <p><strong>14.1. Einhaltung der Ruhezeiten:</strong> Grundsätzlich ist die Verursachung von Lärm im gebuchten Apartment, den gemeinschaftlichen Nutzungsbereichen sowie auf dem umliegenden Gelände zu vermeiden. Die Nachtruhe ist von <strong>22 Uhr bis 6 Uhr</strong> einzuhalten (<strong>„Ruhezeiten“</strong>), sofern die Hausregeln keine abweichenden Zeiten vorgeben.</p>
        <p><strong>14.2. Veranstaltungsverbote:</strong> Das Abhalten von Partys und Versammlungen in den Apartments und Gemeinschaftsbereichen von Cozy Voyage ist strengstens untersagt.</p>
        <p><strong>14.3. Folgen von Veranstaltungsverstößen:</strong> Bei Zuwiderhandlung ist Cozy Voyage berechtigt, vom Gast Schadensersatz für die zusätzlich erforderlichen Reinigungskosten sowie eventuelle Einnahmeausfälle durch eine durch den Vorfall nicht zumutbare Weitervermietung des Apartments in Höhe von <strong>EUR 500,00</strong> zu verlangen. Das Recht auf weitergehenden Schadensersatz wird hiervon nicht berührt. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>14.4. Überwachungseinrichtungen:</strong> In Apartments von Cozy Voyage können Dezibelsensoren verbaut sein. Diese Sensoren zeichnen keine Stimmen oder Gespräche auf, dienen jedoch der Erkennung übermäßiger Lautstärke. In Gemeinschaftsbereichen von Cozy Voyage (z.B. Fluren) können ebenfalls Dezibelsensoren sowie aktive Videoüberwachung installiert sein, die 24/7 aufzeichnet und in einer Cloud-Umgebung speichert.</p>
        <p><strong>14.5. Kündigungsrecht bei Partyverstößen und Kostenweitergabe:</strong> Cozy Voyage ist berechtigt, eine aktive Buchung mit sofortiger Wirkung zu kündigen und Gäste des Hauses zu verweisen, sobald Kenntnis von Zuwiderhandlungen gegen die Punkte 14.1 und 14.2 erlangt wird. Ein Anspruch auf eine Rück- oder Teilerstattung besteht in diesen Fällen nicht. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist. Cozy Voyage behält sich das Recht vor, zur Durchsetzung des Hausrechts die Leistungen eines Dritten, beispielsweise eines Sicherheitsdienstes, in Anspruch zu nehmen. Eventuell anfallende Kosten durch eine solche Intervention werden an den Gast weiterberechnet.</p>

        ---
        <h4>15. Beschädigung oder unberechtigte Entnahme von Inventar</h4>
        <p><strong>15.1. Schadensersatzpflicht:</strong> Sollte es während des Aufenthalts zu Schäden kommen, die über den vertragsgemäßen Gebrauch hinausgehen, oder wird Inventar unberechtigt aus dem Apartment entfernt, hat Cozy Voyage Anspruch auf Schadensersatz. Dieser umfasst insbesondere die Kosten zur Beseitigung des Schadens, einschließlich möglicher Einnahmeausfälle durch eine nicht mögliche Vermietung des Apartments, sowie Kosten der Rechtsverfolgung zuzüglich einer Bearbeitungsgebühr von <strong>50€</strong> für den jeweiligen Schadensfall. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>

        ---
        <h4>16. Haustiere</h4>
        <p><strong>16.1. Haustierverbot und Ausnahmen:</strong> Das Mitbringen von (Haus-)tieren ist in den Apartments und Gemeinschaftsflächen nicht gestattet. Ausnahmen bilden Blinden-, Gehörlosen- sowie vergleichbare Servicehunde, die gegen entsprechenden Nachweis kostenfrei und jederzeit mitgeführt werden dürfen. Der notwendige Nachweis ist dem Cozy Voyage vor dem Check-in eigenständig vorzulegen.</p>
        <p><strong>16.2. Folgen ungenehmigter Haustiere:</strong> Cozy Voyage ist berechtigt, vom vorgenannten Grundsatz weitere Ausnahmen zu machen, jedoch besteht hierauf kein Anspruch des Gastes. Befindet sich ein Haustier ohne Genehmigung in einem Apartment, werden pauschal <strong>EUR 150,00</strong> als Sonderreinigungsgebühr seitens Cozy Voyage in Rechnung gestellt. Cozy Voyage ist berechtigt, eine aktive Buchung mit sofortiger Wirkung zu kündigen und den Gast des Hauses zu verweisen, wenn Verstöße gegen Punkt 16.1 vorliegen. Ein Anspruch auf eine Rück- oder Teilerstattung besteht in diesen Fällen nicht. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>

        ---
        <h4>17. Instandhaltung und Sorgfaltspflicht</h4>
        <p><strong>17.1. Pflicht zur pfleglichen Behandlung und Reinigungskosten:</strong> Mit der Buchung eines Apartments von Cozy Voyage verpflichtet sich der Gast, das überlassene Apartment sowie alle zur gemeinschaftlichen Nutzung vorgesehenen Räume, Einrichtungen und Anlagen schonend und pfleglich zu behandeln, für eine ausreichende Lüftung und Heizung zu sorgen und grobe Verschmutzungen zu vermeiden. Sollten während des Aufenthalts des Gastes oder nach dessen Abreise Verschmutzungen festgestellt werden, die über den üblichen Gebrauch hinausgehen, ist Cozy Voyage berechtigt, dem Gast eine zusätzliche Reinigungsgebühr von mindestens <strong>EUR 50,00</strong> (abhängig vom Zustand des Apartments) in Rechnung zu stellen. Dem Gast bleibt der Nachweis gestattet, dass Cozy Voyage ein geringerer oder kein Schaden entstanden ist.</p>
        <p><strong>17.2. Überprüfung bei Bezug und Mängelanzeige:</strong> Der Gast verpflichtet sich ferner, die Ausstattung des Apartments bei Bezug auf Vollständigkeit und Gebrauchstauglichkeit zu überprüfen und etwaige Mängel oder Beanstandungen Cozy Voyage unverzüglich mitzuteilen.</p>
        <p><strong>17.3. Haftung für Schäden:</strong> Der Gast haftet für sämtliche Schäden am ihm überlassenen Apartment, den Einrichtungsgegenständen sowie den zur gemeinschaftlichen Nutzung bestimmten Räumen, Einrichtungen und Anlagen, die er oder seine Besucher durch vertragswidrige Nutzung schuldhaft verursacht haben und die nicht auf normale Abnutzung zurückzuführen sind. Alle am überlassenen Apartment entstandenen Schäden sind Cozy Voyage unverzüglich anzuzeigen.</p>
        <p><strong>17.4. Zwischenreinigungen bei längeren Aufenthalten:</strong> Bei Buchungen von mehr als 7 Nächten ist Cozy Voyage berechtigt, wöchentliche Zwischenreinigungen durchzuführen. Der Gast ist verpflichtet, dem von Cozy Voyage beauftragten Dienstleister oder Mitarbeitern von Cozy Voyage zu diesem Zweck Zugang zum Apartment zu gewähren.</p>

        ---
        <h4>18. Internetzugang und dessen Nutzung</h4>
        <p><strong>18.1. Bereitstellung des Internetzugangs:</strong> Cozy Voyage stellt dem Gast im Rahmen der technisch und betrieblich gegebenen Möglichkeiten einen Internetzugang zur Verfügung. Ausfälle, beispielsweise durch höhere Gewalt, Wartungsarbeiten oder Ähnliches, können nicht ausgeschlossen werden.</p>
        <p><strong>18.2. Verbot missbräuchlicher Nutzung:</strong> Der Gast darf den Internetanschluss nicht missbräuchlich nutzen. Eine missbräuchliche Nutzung liegt insbesondere vor bei: dem Download und der Verbreitung urheberrechtlich geschützter Inhalte über Peer-to-Peer-Plattformen, der Nutzung illegaler Streaming-Angebote sowie dem Einstellen, Abrufen oder Übermitteln strafrechtlich relevanter Inhalte (insbesondere gemäß §§ 130, 130a, 131 und 184 StGB). Der Gast ist verpflichtet, bei der Nutzung die Urheber-, Patent-, Namens-, Kennzeichen- und Persönlichkeitsrechte Dritter zu respektieren. Der Gast stellt Cozy Voyage auf erstes Anfordern von allen Ansprüchen und Schadensersatzforderungen Dritter sowie von den Kosten der Rechtsverteidigung in angemessener Höhe frei, die durch eine rechtswidrige Nutzung des zur Verfügung gestellten Internetanschlusses durch den Gast oder durch Dritte mit Wissen des Gastes entstanden sind. Dieser Freistellungsanspruch umfasst insbesondere Ansprüche aus der Verletzung von Urheber-, Patent-, Namens-, Kennzeichen- und Persönlichkeitsrechten sowie Datenschutzverstöße.</p>
        <p><strong>18.3. Untersagung der Weitergabe von Zugangsdaten:</strong> Die Weitergabe der Zugangsdaten für den Internetanschluss von Cozy Voyage an Dritte ist dem Gast untersagt. Dies gilt auch für die Veröffentlichung solcher Zugangsdaten. Bei Zuwiderhandlung haftet der Gast für alle Cozy Voyage durch die Weitergabe der Zugangsdaten entstandenen Schäden.</p>
        <p><strong>18.4. Sperrung des Internetzugangs:</strong> Im Übrigen behält sich Cozy Voyage das Recht vor, den Internetzugang des Gastes bei Rechtsverstößen zu sperren.</p>

        ---
        <h4>19. Datenschutzbestimmungen</h4>
        <p><strong>19.1. Informationen zum Datenschutz:</strong> Die detaillierten Datenschutzbestimmungen von Cozy Voyage sind unter folgendem Link einsehbar: [<strong>Hier den tatsächlichen Link zur Datenschutzrichtlinie von Cozy Voyage einfügen</strong>]</p>

        ---
        <h4>20. Schlussbestimmungen</h4>
        <p><strong>20.1. Form von Änderungen und Aufhebungen:</strong> Änderungen und Ergänzungen sowie die Aufhebung des Beherbergungsvertrages, der Antragsannahme oder dieser Allgemeinen Geschäftsbedingungen bedürfen der Textform. Dies gilt auch für die Abänderung dieser Textformklausel. Einseitige Änderungen oder Ergänzungen durch den Gast sind unwirksam.</p>
        <p><strong>20.2. Erfüllungsort und Zahlungsort:</strong> Erfüllungs- und Zahlungsort ist der Sitz des Beherbergungsbetriebs von Cozy Voyage.</p>
        <p><strong>20.3. Gerichtsstand:</strong> Ausschließlicher Gerichtsstand im kaufmännischen Verkehr ist der Sitz des Beherbergungsbetriebs. Sofern ein Vertragspartner die Voraussetzungen des § 38 Abs. 2 ZPO erfüllt und keinen allgemeinen Gerichtsstand im Inland hat, gilt ebenfalls der Sitz des Beherbergungsbetriebs als Gerichtsstand.</p>
        <p><strong>20.4. Anwendbares Recht:</strong> Es gilt ausschließlich deutsches Recht. Die Anwendung des UN-Kaufrechts und des Kollisionsrechts ist ausgeschlossen.</p>
        <p><strong>20.5. Salvatorische Klausel:</strong> Sollte eine Bestimmung dieses Vertrages ganz oder teilweise unwirksam oder nichtig sein oder werden, so wird die Wirksamkeit der übrigen Bestimmungen davon nicht berührt. Anstelle der unwirksamen/nichtigen Bestimmung werden die Parteien eine solche Bestimmung treffen, die dem mit der unwirksamen/nichtigen Bestimmung ursprünglich beabsichtigten wirtschaftlichen Zweck am nächsten kommt. Dies gilt entsprechend für die Ausfüllung etwaiger Vertragslücken.</p>
        <p><strong>20.6. Verbraucherschlichtung:</strong> Cozy Voyage ist weder bereit noch verpflichtet, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.</p>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
