import type {Metadata} from 'next';
import { League_Spartan } from 'next/font/google';
import {HeroUIProvider} from "@heroui/react";
import './globals.scss';
import 'leaflet/dist/leaflet.css';

const leagueSpartanSans = League_Spartan({
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
        <body className={leagueSpartanSans.className}>
        <HeroUIProvider>
            {children}
        </HeroUIProvider>
        </body>
        </html>
    );
}
