name: Build and Deploy Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t cozy-voyage:latest .

      - name: Save Docker image as tar
        run: |
          mkdir -p output
          docker save cozy-voyage:latest -o output/cozy-voyage.tar
          chmod 644 output/cozy-voyage.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: output/cozy-voyage.tar
          target: ~/cozy-voyage.tar

      - name: Load Docker image and run container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker load -i ~/cozy-voyage.tar
            docker stop cozy-voyage || true
            docker rm cozy-voyage || true
            docker run -d --name cozy-voyage -p 3011:3011 cozy-voyage:latest

