jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t cozy-voyage:latest .

      - name: Save Docker image as tar
        run: |
          mkdir -p output
          docker save cozy-voyage:latest -o output/cozy-voyage.tar
          chmod 644 output/cozy-voyage.tar

      - name: Clean remote target path
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            rm -rf ~/cozy-voyage.tar

      - name: Upload Docker tar file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          source: output/cozy-voyage.tar
          target: ~

      - name: Load image and start container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            docker load -i ~/cozy-voyage.tar
            docker stop cozy-voyage || true
            docker rm cozy-voyage || true
            docker run -d --name cozy-voyage -p 3011:3011 --restart unless-stopped cozy-voyage:latest
